const dummyData = {
   articles:[
   {
   _id: "12f5504c4998440063afe3aef55b8209",
   _score: 24.82406,
   author: "Grace Dean",
   authors: ["Grace Dean"],
   clean_url: "businessinsider.com",
   country: "US",
   is_opinion: false,
   language: "en",
   link: "https://www.businessinsider.com/elon-musk-spacex-dogecoin-moon-crypto-cryptocurrencies-2021-4",
   media: "https://i.insider.com/6065ab84daf0f10018f9967b?width=1200&format=jpeg",
   published_date: "2021-04-01 11:40:02",
   published_date_precision: "full",
   rank: 110,
   rights: "businessinsider.com",
   summary: "SpaceX CEO Elon Musk tweeted on Thursday that the aerospace company plans to put \"a literal Dogecoin on the literal moon.\"—Elon Musk (@elonmusk) April 1, 2021Musk is a vocal fan of the cryptocurrency, and has even bought some for his nine-month old son.He frequently tweets memes starring Shibu Inus, the \"doge\" dog breed that gives the cryptocurrency its icon and name. He has also said that he plans to buy a Shibu Inu.Read more: Elon Musk is pumping stocks, cryptocurrencies, and the energy of 49 ",
   title: "Elon Musk says that SpaceX is going to 'put a literal Dogecoin on the literal moon'",
   topic: "news",
   twitter_account: null,
   },
   {
   _id: "899741d008b00ad8d2ca0d04581fa334",
   _score: 22.544588,
   author: "Kate Duffy",
   authors: ["Kate Duffy"],
   clean_url: "businessinsider.com",
   country: "US",
   is_opinion: false,
   language: "en",
   link: "https://www.businessinsider.com/elon-musk-surprise-texas-brownsville-donation-revitalize-area-spacex-2021-4",
   media: "https://i.insider.com/5fe4d819edf8920018093b41?width=1200&format=jpeg",
   published_date: "2021-04-01 10:17:43",
   published_date_precision: "full",
   rank: 110,
   rights: "businessinsider.com",
   summary: "A Texas city was taken by surprised when Elon Musk tweeted on Tuesday that he would donate $30 million to revitalize it and its schools, after appealing for people to move there to work for SpaceX.He tweeted that he was donating $20 million to schools in Cameron County and $10 million to revitalize downtown Brownsville, home to one of the company's rocket production facilities and close to the launch site in Boca Chica, which Musk has said he wants to grow into a city called \"Starbase.\"Musk adde",
   title: "Elon Musk takes Texas city by surprise by tweeting he's going to donate $30 million to boost the area",
   topic: "news",
   twitter_account: "@sai",
   },
   {
   _id: "1e2cd82d1f8f1e02b87adf57e1d03fad",
   _score: 21.252316,
   author: "Callum Jones, US Business Correspondent",
   authors: ["Callum Jones", "US Business Correspondent"],
   clean_url: "thetimes.co.uk",
   country: "GB",
   is_opinion: false,
   language: "en",
   link: "https://www.thetimes.co.uk/article/elon-musk-nominated-to-board-of-endeavor-jvhgc0jvs",
   media: "https://www.thetimes.co.uk/imageserver/image/%2Fmethode%2Ftimes%2Fprod%2Fweb%2Fbin%2Fcbbce092-930b-11eb-af3b-900f1f5fe235.jpg?crop=4300%2C2419%2C0%2C224&resize=685",
   published_date: "2021-04-01 23:01:00",
   published_date_precision: "full",
   rank: 529,
   rights: "thetimes.co.uk",
   summary: "Elon Musk has been lined up to join the board of a Hollywood conglomerate behind the Miss Universe pageant, New York Fashion Week and the Ultimate Fighting Championship.The Tesla chief executive has been nominated to become a board director at Endeavor, which has revived plans for a stock market listing.Endeavor also plans to raise almost $1.8 billion via a private placement to buy the minority stake in UFC that it does not own.WME, its talent agency, represents celebrities including Dwayne John",
   title: "Elon Musk nominated to board of Endeavor",
   topic: "news",
   twitter_account: null,
   },
   {
   _id: "b15ef212b77e2090373d08249e038a2a",
   _score: 20.961115,
   author: null,
   authors: [],
   clean_url: "iheart.com",
   country: null,
   is_opinion: false,
   language: "en",
   link: "https://woai.iheart.com/content/2021-03-31-elon-pushes-starbase-to-space-industry-job-seekers/",
   media: "https://i.iheart.com/v3/re/new_assets/5dd68d89aa3e0289fd3fa398?ops=gravity(%22north%22),fit(740,416),quality(65)",
   published_date: "2021-03-31 10:15:00",
   published_date_precision: "full",
   rank: 883,
   rights: "iheart.com",
   summary: "SpaceX CEO Elon Musk wants space industry job seekers to consider a move to the Rio Grande Valley. Yesterday, Musk tweeted the message to encourage \"engineers, technicians, builders and essential support personnel of all kinds\" to move to the Valley to work. Musk refers to the area as Starbase which is at the SpaceX Boca Chica test site near Brownsville and South Padre Island. Musk intends to grow the area by several thousand new residents with technical backgrounds within the next few years. Ph",
   title: "Elon Pushes Starbase To Space Industry Job Seekers",
   topic: "news",
   twitter_account: "@963KHEYCOUNTRY",
   },
   {
   _id: "5e520b611379c1455cadb0164f3eb096",
   _score: 20.820152,
   author: "Kalyan Parbat",
   authors:["Kalyan Parbat"],
   clean_url: "indiatimes.com",
   country: "IN",
   is_opinion: false,
   language: "en",
   link: "https://economictimes.indiatimes.com/industry/telecom/telecom-news/elon-musks-satellite-net-plan-in-india-hits-a-bump/articleshow/81797649.cms",
   media: "https://img.etimg.com/thumb/msid-81806160,width-1070,height-580/photo.jpg",
   published_date: "2021-04-01 04:28:00",
   published_date_precision: "timezone unknown",
   rank: 325,
   rights: "indiatimes.com",
   summary: "Elon Musk-founded SpaceX Technologies' bid for an initial India foray into satellite broadband faces its first challenge. An industry body representing the likes of Amazon, Hughes, Google, Microsoft and Facebook has written to the Telecom Regulatory Authority of India (Trai) and the Indian Space Research Organisation (Isro) asking them to stop SpaceX from pre-selling the beta version of its Starlink satellite internet services in India. It",
   title: "Elon Musk's satellite net plan in India hits a bump",
   topic: "economics",
   twitter_account: "@EconomicTimes",
   },
   {
   _id: "a157c699dad7f0af805766e6c672dae7",
   _score: 20.802174,
   author: "Alex Sherman",
   authors: ["Some Person"],
   clean_url: "cnbc.com",
   country: "US",
   is_opinion: false,
   language: "en",
   link: "https://www.cnbc.com/2021/03/31/elon-musk-tapped-to-join-endeavor-group-as-new-board-member.html",
   media: "https://i2.wp.com/media.nbcmiami.com/2021/02/106836975-1612791996353-gettyimages-1206289333-SATELLITE_2020.jpeg?quality=85&resize=1200%2C675&strip=all&ssl=1",
   published_date: "2021-03-31 20:14:41",
   published_date_precision: "timezone unknown",
   rank: 143,
   rights: "nbcmiami.com",
   summary: "Endeavor Group said in its IPO prospectus that it plans to add Elon Musk as a new member of its board of directors. Musk has connections to Endeavor co-founder Ari Emanuel. Endeavor is filing to go public after scrapping its IPO in 2019. Elon Musk is about to increase his already hefty workload. Musk, the CEO of Tesla and SpaceX and founder of The Boring Company and Neuralink, has been nominated to join the board at Endeavor Group Holdings, according to a filing by the company on Wednesday. Ende",
   title: "Elon Musk Tapped to Join Board of Endeavor Group, Owner of UFC and Miss Universe Contest",
   topic: "business",
   twitter_account: "@nbc6",
   },
   {
   _id: "b2e9b3fae99039bba6d2e841b3b5521d",
   _score: 20.766588,
   author: "Laura Leavitt",
   authors: ["Laura Leavitt"],
   clean_url :"cnet.com",
   country :"US",
   is_opinion :false,
   language :"en",
   link :"https://www.cnet.com/home/internet/hughesnet-viasat-and-elon-musk-satellite-internet-explained/",
   media :"https://www.cnet.com/a/img/8zKMYxDp3jmAsMh102fZA__oNpo=/1200x630/2021/03/30/6b12f6b7-6222-4dd7-9c42-5d63546d02dd/dsc06258.jpg",
   published_date :"2021-03-31 20:20:26",
   published_date_precision :"full",
   rank :132,
   rights :"cnet.com",
   summary :"Viasat is a long-established option for satellite internet -- but it's facing new competition in 2021. Rafael Henrique/SOPA Images/LightRocket/Getty Images Satellite internet is nothing new, but there's growing interest in the category now that Amazon, Elon Musk and others are working to expand its availability and capabilities. That's welcome news, especially with the ongoing pandemic keeping people at home, and more dependent on internet access than ever before. Available in all 50 states",
   title :"HughesNet, Viasat and... Elon Musk? Satellite internet, explained",
   topic :"news",
   twitter_account :"@CNET"},
],
   page :1,
   page_size :25,
   status :"ok",
   total_hits :332,
   total_pages :14,
   user_input :{
   from :"2021-03-26 00:00:00",
   lang :"en",
   page :1,
   q :"Elon Musk",
   size:25,
   sort_by :"relevancy",
   }
};

export {dummyData};